SELECT * FROM tabla_de_productos;

SELECT NOMBRE_DEL_PRODUCTO, PRECIO_DE_LISTA,
CASE
	WHEN PRECIO_DE_LISTA >= 12 THEN 'COSTOSO'
    WHEN PRECIO_DE_LISTA >= 5 AND PRECIO_DE_LISTA <12 THEN 'ASEQUIBLE'
    ELSE 'BARATO'
END AS PRECIO
FROM tabla_de_productos;

SELECT ENVASE, SABOR,
CASE
	WHEN PRECIO_DE_LISTA >= 12 THEN 'COSTOSO'
    WHEN PRECIO_DE_LISTA >= 5 AND PRECIO_DE_LISTA < 12 THEN 'ASEQUIBLE'
    ELSE 'BARATO'
END AS PRECIO, MIN(PRECIO_DE_LISTA) AS PRECIO_MINIMO
FROM tabla_de_productos
WHERE TAMANO = '700 ml'
GROUP BY ENVASE,
CASE
	WHEN PRECIO_DE_LISTA >= 12 THEN 'COSTOSO'
    WHEN PRECIO_DE_LISTA >= 5 AND PRECIO_DE_LISTA < 12 THEN 'ASEQUIBLE'
    ELSE 'BARATO'
END
ORDER BY ENVASE; 

SELECT NOMBRE,FECHA_DE_NACIMIENTO,
CASE
	WHEN YEAR(FECHA_DE_NACIMIENTO) > 1995 THEN 'Niños'
    WHEN YEAR(FECHA_DE_NACIMIENTO) >= 1990 AND YEAR(FECHA_DE_NACIMIENTO) <= 1995 THEN 'Jovenes'
    WHEN YEAR(FECHA_DE_NACIMIENTO) < 1990 THEN 'Viejos'
END AS RANGO_EDAD
FROM tabla_de_clientes;

